const NearestColor = require('./nearestColor')

(function() {
  const getMappedData = () => {
    let rgbMap = {}

    rgbData.forEach((item) => {
        let category
        const categoryCode = item.ComplexionCode[0]
        if (categoryCode === "F") category = 'Fair'
        if (categoryCode === "L") category = 'Light'
        if (categoryCode === "T") category = "Tan"
        if (categoryCode === "M") category = "Medium"
        if (categoryCode === "D") category = "Dark"
        if (categoryCode === "P") category = "Deep"
        
        rgbMap[item.ComplexionCode] = {
            imageCode: item.ImageCode,
            complexionCode: item.ComplexionCode,
            color1: item.Color1,
            color2: item.Color2,
            color3: item.Color3,
            part1: item.Part1,
            part2: item.Part2,
            part3: item.Part3,
            r: item.R,
            g: item.G,
            b: item.B,
            category,
            rgb: `rgb-${item.R}-${item.G}-${item.B}`,
        }
    })

    return rgbMap
}   

const rgbData = [
    {
      "ImageCode": "D212B",
      "Color1": "P11",
      "Color2": "D22",
      "Color3": "P13",
      "Part1": 2,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAW",
      "R": 104,
      "G": 67,
      "B": 45,
      "Category": "Dark",
      "": ""
    },
    {
      "ImageCode": "F11D",
      "Color1": "F23",
      "Color2": "F11",
      "Color3": "F12",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "FAAM",
      "R": 220,
      "G": 190,
      "B": 162,
      "": ""
    },
    {
      "ImageCode": "F23A",
      "Color1": "F11",
      "Color2": "F22",
      "Color3": "F23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "FAAM",
      "R": 220,
      "G": 190,
      "B": 162,
      "": ""
    },
    {
      "ImageCode": "F21E",
      "Color1": "F21",
      "Color2": "F13",
      "Color3": "L15",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "FAAQ",
      "R": 219,
      "G": 183,
      "B": 151,
      "": ""
    },
    {
      "ImageCode": "L315B",
      "Color1": "M13",
      "Color2": "M15",
      "Color3": "L31",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0.5,
      "ComplexionCode": "LAAR",
      "R": 200,
      "G": 162,
      "B": 129,
      "": ""
    },
    {
      "ImageCode": "L231C",
      "Color1": "L35",
      "Color2": "L21",
      "Color3": "L23",
      "Part1": 0,
      "Part2": 0.5,
      "Part3": 1,
      "ComplexionCode": "LABT",
      "R": 210,
      "G": 172,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "D21B",
      "Color1": "D21",
      "Color2": "P12",
      "Color3": "D15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAK",
      "R": 108,
      "G": 70,
      "B": 47,
      "": ""
    },
    {
      "ImageCode": "D21E",
      "Color1": "D21",
      "Color2": "P12",
      "Color3": "P25",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAK",
      "R": 108,
      "G": 70,
      "B": 47,
      "": ""
    },
    {
      "ImageCode": "D113A",
      "Color1": "D11",
      "Color2": "D13",
      "Color3": "D25",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAM",
      "R": 121,
      "G": 83,
      "B": 57,
      "": ""
    },
    {
      "ImageCode": "D113B",
      "Color1": "T23",
      "Color2": "D25",
      "Color3": "D11",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DAAN",
      "R": 146,
      "G": 102,
      "B": 67,
      "": ""
    },
    {
      "ImageCode": "D121B",
      "Color1": "T31",
      "Color2": "D12",
      "Color3": "D25",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAP",
      "R": 148,
      "G": 99,
      "B": 63,
      "": ""
    },
    {
      "ImageCode": "D123A",
      "Color1": "D13",
      "Color2": "D22",
      "Color3": "D25",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAQ",
      "R": 114,
      "G": 78,
      "B": 56,
      "": ""
    },
    {
      "ImageCode": "D125A",
      "Color1": "D11",
      "Color2": "T22",
      "Color3": "D15",
      "Part1": 0,
      "Part2": 1,
      "Part3": 0.5,
      "ComplexionCode": "DAAR",
      "R": 160,
      "G": 115,
      "B": 79,
      "": ""
    },
    {
      "ImageCode": "D21C",
      "Color1": "M12",
      "Color2": "D21",
      "Color3": "D15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAT",
      "R": 164,
      "G": 120,
      "B": 89,
      "": ""
    },
    {
      "ImageCode": "D21D",
      "Color1": "D21",
      "Color2": "D22",
      "Color3": "P15",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DAAV",
      "R": 115,
      "G": 79,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D13A",
      "Color1": "D13",
      "Color2": "D12",
      "Color3": "D21",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DAAX",
      "R": 114,
      "G": 79,
      "B": 56,
      "": ""
    },
    {
      "ImageCode": "D221A",
      "Color1": "D21",
      "Color2": "P12",
      "Color3": "D23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DAAZ",
      "R": 110,
      "G": 75,
      "B": 54,
      "": ""
    },
    {
      "ImageCode": "D221B",
      "Color1": "D21",
      "Color2": "D24",
      "Color3": "P12",
      "Part1": 0.5,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DABA",
      "R": 104,
      "G": 66,
      "B": 46,
      "": ""
    },
    {
      "ImageCode": "D221C",
      "Color1": "P11",
      "Color2": "P14",
      "Color3": "D22",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DABB",
      "R": 108,
      "G": 70,
      "B": 46,
      "": ""
    },
    {
      "ImageCode": "D225A",
      "Color1": "T33",
      "Color2": "T32",
      "Color3": "D25",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "DABC",
      "R": 144,
      "G": 102,
      "B": 69,
      "": ""
    },
    {
      "ImageCode": "D235A",
      "Color1": "D25",
      "Color2": "D11",
      "Color3": "T23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DABD",
      "R": 146,
      "G": 106,
      "B": 73,
      "": ""
    },
    {
      "ImageCode": "D235B",
      "Color1": "D13",
      "Color2": "D25",
      "Color3": "T32",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DABE",
      "R": 120,
      "G": 87,
      "B": 63,
      "": ""
    },
    {
      "ImageCode": "D114A",
      "Color1": "D11",
      "Color2": "D25",
      "Color3": "D12",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DAAO",
      "R": 136,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D212A",
      "Color1": "D25",
      "Color2": "D12",
      "Color3": "D11",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "DAAO",
      "R": 136,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D125C",
      "Color1": "T32",
      "Color2": "D15",
      "Color3": "T23",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAS",
      "R": 156,
      "G": 111,
      "B": 73,
      "": ""
    },
    {
      "ImageCode": "D125D",
      "Color1": "T32",
      "Color2": "D15",
      "Color3": "T31",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAS",
      "R": 156,
      "G": 111,
      "B": 73,
      "": ""
    },
    {
      "ImageCode": "D135A",
      "Color1": "T22",
      "Color2": "T23",
      "Color3": "D15",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "DAAU",
      "R": 158,
      "G": 114,
      "B": 76,
      "": ""
    },
    {
      "ImageCode": "D135B",
      "Color1": "D15",
      "Color2": "T11",
      "Color3": "T23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DAAU",
      "R": 158,
      "G": 114,
      "B": 76,
      "": ""
    },
    {
      "ImageCode": "D135C",
      "Color1": "D15",
      "Color2": "T11",
      "Color3": "T23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DAAU",
      "R": 158,
      "G": 114,
      "B": 76,
      "": ""
    },
    {
      "ImageCode": "D214B",
      "Color1": "D21",
      "Color2": "D25",
      "Color3": "D22",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "DAAY",
      "R": 122,
      "G": 80,
      "B": 50,
      "": ""
    },
    {
      "ImageCode": "D215A",
      "Color1": "D21",
      "Color2": "D22",
      "Color3": "P15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "DAAY",
      "R": 122,
      "G": 80,
      "B": 50,
      "": ""
    },
    {
      "ImageCode": "D241B",
      "Color1": "D25",
      "Color2": "D21",
      "Color3": "D22",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "DAAY",
      "R": 122,
      "G": 80,
      "B": 50,
      "": ""
    },
    {
      "ImageCode": "F112A",
      "Color1": "L15",
      "Color2": "F12",
      "Color3": "F11",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "FAAL",
      "R": 230,
      "G": 194,
      "B": 168,
      "": ""
    },
    {
      "ImageCode": "F11B",
      "Color1": "F11",
      "Color2": "F12",
      "Color3": "F23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "FAAM",
      "R": 220,
      "G": 190,
      "B": 162,
      "": ""
    },
    {
      "ImageCode": "F11C",
      "Color1": "F13",
      "Color2": "F22",
      "Color3": "F11",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "FAAN",
      "R": 221,
      "G": 191,
      "B": 166,
      "": ""
    },
    {
      "ImageCode": "F13D",
      "Color1": "F13",
      "Color2": "F25",
      "Color3": "F12",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "FAAO",
      "R": 221,
      "G": 191,
      "B": 163,
      "": ""
    },
    {
      "ImageCode": "F13F",
      "Color1": "L15",
      "Color2": "F13",
      "Color3": "F21",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "FAAP",
      "R": 216,
      "G": 186,
      "B": 157,
      "": ""
    },
    {
      "ImageCode": "F21D",
      "Color1": "F21",
      "Color2": "F22",
      "Color3": "L15",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "FAAQ",
      "R": 219,
      "G": 183,
      "B": 151,
      "": ""
    },
    {
      "ImageCode": "F23B",
      "Color1": "F12",
      "Color2": "F23",
      "Color3": "F15",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "FAAR",
      "R": 224,
      "G": 195,
      "B": 165,
      "": ""
    },
    {
      "ImageCode": "F23D",
      "Color1": "F15",
      "Color2": "F22",
      "Color3": "F23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "FAAR",
      "R": 224,
      "G": 195,
      "B": 165,
      "": ""
    },
    {
      "ImageCode": "F23F",
      "Color1": "L15",
      "Color2": "F22",
      "Color3": "L23",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "FAAS",
      "R": 216,
      "G": 177,
      "B": 149,
      "": ""
    },
    {
      "ImageCode": "L213C",
      "Color1": "L21",
      "Color2": "L23",
      "Color3": "F24",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAS",
      "R": 212,
      "G": 172,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L213D",
      "Color1": "L23",
      "Color2": "L21",
      "Color3": "F22",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAS",
      "R": 212,
      "G": 172,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L213E",
      "Color1": "L23",
      "Color2": "L21",
      "Color3": "L15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAS",
      "R": 212,
      "G": 172,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L213G",
      "Color1": "L23",
      "Color2": "L21",
      "Color3": "M15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAS",
      "R": 212,
      "G": 172,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L213C",
      "Color1": "L21",
      "Color2": "L23",
      "Color3": "F24",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAS",
      "R": 212,
      "G": 172,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L113C",
      "Color1": "L11",
      "Color2": "L13",
      "Color3": "F12",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAU",
      "R": 215,
      "G": 179,
      "B": 147,
      "": ""
    },
    {
      "ImageCode": "L113D",
      "Color1": "L11",
      "Color2": "F22",
      "Color3": "L13",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LAAU",
      "R": 215,
      "G": 179,
      "B": 147,
      "": ""
    },
    {
      "ImageCode": "L11K",
      "Color1": "L11",
      "Color2": "L35",
      "Color3": "L13",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LAAU",
      "R": 215,
      "G": 179,
      "B": 147,
      "": ""
    },
    {
      "ImageCode": "L11A",
      "Color1": "L11",
      "Color2": "L23",
      "Color3": "L35",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAV",
      "R": 212,
      "G": 174,
      "B": 144,
      "": ""
    },
    {
      "ImageCode": "L213H",
      "Color1": "L11",
      "Color2": "L23",
      "Color3": "M15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAV",
      "R": 212,
      "G": 174,
      "B": 144,
      "": ""
    },
    {
      "ImageCode": "L11E",
      "Color1": "L11",
      "Color2": "F22",
      "Color3": "F25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LAAW",
      "R": 221,
      "G": 185,
      "B": 152,
      "": ""
    },
    {
      "ImageCode": "L11F",
      "Color1": "L11",
      "Color2": "F25",
      "Color3": "F23",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAW",
      "R": 221,
      "G": 185,
      "B": 152,
      "": ""
    },
    {
      "ImageCode": "L11N",
      "Color1": "L11",
      "Color2": "F25",
      "Color3": "L23",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAW",
      "R": 221,
      "G": 185,
      "B": 152,
      "": ""
    },
    {
      "ImageCode": "L11G",
      "Color1": "F21",
      "Color2": "L12",
      "Color3": "L23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LAAX",
      "R": 214,
      "G": 178,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L23B",
      "Color1": "L23",
      "Color2": "F12",
      "Color3": "F21",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LAAX",
      "R": 214,
      "G": 178,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L11H",
      "Color1": "F21",
      "Color2": "L15",
      "Color3": "F22",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LAAY",
      "R": 219,
      "G": 183,
      "B": 151,
      "": ""
    },
    {
      "ImageCode": "L11I",
      "Color1": "L23",
      "Color2": "L11",
      "Color3": "L35",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LAAZ",
      "R": 214,
      "G": 176,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L11L",
      "Color1": "L11",
      "Color2": "L23",
      "Color3": "L35",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LAAZ",
      "R": 214,
      "G": 176,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L35C",
      "Color1": "F23",
      "Color2": "L11",
      "Color3": "L35",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LAAZ",
      "R": 214,
      "G": 176,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L11J",
      "Color1": "L11",
      "Color2": "L15",
      "Color3": "L33",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LABA",
      "R": 217,
      "G": 180,
      "B": 147,
      "": ""
    },
    {
      "ImageCode": "L11P",
      "Color1": "L11",
      "Color2": "L25",
      "Color3": "F23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABB",
      "R": 215,
      "G": 182,
      "B": 151,
      "": ""
    },
    {
      "ImageCode": "L11Q",
      "Color1": "F23",
      "Color2": "L35",
      "Color3": "L11",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABB",
      "R": 215,
      "G": 182,
      "B": 151,
      "": ""
    },
    {
      "ImageCode": "L11S",
      "Color1": "L35",
      "Color2": "L11",
      "Color3": "F23",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LABB",
      "R": 215,
      "G": 182,
      "B": 151,
      "": ""
    },
    {
      "ImageCode": "L11T",
      "Color1": "L11",
      "Color2": "L13",
      "Color3": "L25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABC",
      "R": 217,
      "G": 179,
      "B": 144,
      "": ""
    },
    {
      "ImageCode": "L12B",
      "Color1": "L35",
      "Color2": "L13",
      "Color3": "L12",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LABD",
      "R": 217,
      "G": 178,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L12C",
      "Color1": "L21",
      "Color2": "L12",
      "Color3": "F25",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LABE",
      "R": 218,
      "G": 174,
      "B": 143,
      "": ""
    },
    {
      "ImageCode": "L12D",
      "Color1": "F23",
      "Color2": "L12",
      "Color3": "L15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LABF",
      "R": 217,
      "G": 181,
      "B": 152,
      "": ""
    },
    {
      "ImageCode": "L13C",
      "Color1": "F21",
      "Color2": "L25",
      "Color3": "L13",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABG",
      "R": 217,
      "G": 182,
      "B": 151,
      "": ""
    },
    {
      "ImageCode": "L13H",
      "Color1": "L13",
      "Color2": "F21",
      "Color3": "L15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LABG",
      "R": 217,
      "G": 182,
      "B": 151,
      "": ""
    },
    {
      "ImageCode": "L13D",
      "Color1": "L31",
      "Color2": "L35",
      "Color3": "L13",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABH",
      "R": 211,
      "G": 173,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L13E",
      "Color1": "L31",
      "Color2": "L35",
      "Color3": "L13",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABH",
      "R": 211,
      "G": 173,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L13F",
      "Color1": "L13",
      "Color2": "L11",
      "Color3": "F22",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABI",
      "R": 219,
      "G": 181,
      "B": 152,
      "": ""
    },
    {
      "ImageCode": "L15B",
      "Color1": "L15",
      "Color2": "L21",
      "Color3": "F22",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABJ",
      "R": 221,
      "G": 182,
      "B": 152,
      "": ""
    },
    {
      "ImageCode": "L213F",
      "Color1": "L31",
      "Color2": "L23",
      "Color3": "L25",
      "Part1": 0.5,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LABK",
      "R": 208,
      "G": 170,
      "B": 139,
      "": ""
    },
    {
      "ImageCode": "L215B",
      "Color1": "L23",
      "Color2": "M15",
      "Color3": "L21",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LABL",
      "R": 210,
      "G": 169,
      "B": 134,
      "": ""
    },
    {
      "ImageCode": "L215C",
      "Color1": "M13",
      "Color2": "L35",
      "Color3": "L21",
      "Part1": 0,
      "Part2": 1,
      "Part3": 2,
      "ComplexionCode": "LABM",
      "R": 215,
      "G": 174,
      "B": 138,
      "": ""
    },
    {
      "ImageCode": "L21A",
      "Color1": "L21",
      "Color2": "M15",
      "Color3": "L13",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABN",
      "R": 215,
      "G": 177,
      "B": 144,
      "": ""
    },
    {
      "ImageCode": "L21G",
      "Color1": "L25",
      "Color2": "L21",
      "Color3": "L13",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LABO",
      "R": 217,
      "G": 177,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L21H",
      "Color1": "L32",
      "Color2": "L21",
      "Color3": "F23",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LABP",
      "R": 215,
      "G": 180,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L223C",
      "Color1": "L22",
      "Color2": "L35",
      "Color3": "L23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABQ",
      "R": 211,
      "G": 170,
      "B": 141,
      "": ""
    },
    {
      "ImageCode": "L22B",
      "Color1": "L15",
      "Color2": "F11",
      "Color3": "L22",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LABR",
      "R": 220,
      "G": 181,
      "B": 153,
      "": ""
    },
    {
      "ImageCode": "L231B",
      "Color1": "L11",
      "Color2": "L35",
      "Color3": "L23",
      "Part1": 0.5,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABS",
      "R": 210,
      "G": 173,
      "B": 143,
      "": ""
    },
    {
      "ImageCode": "L231E",
      "Color1": "L33",
      "Color2": "L32",
      "Color3": "L21",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0.5,
      "ComplexionCode": "LABU",
      "R": 208,
      "G": 169,
      "B": 137,
      "": ""
    },
    {
      "ImageCode": "L235B",
      "Color1": "F25",
      "Color2": "L23",
      "Color3": "L11",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LABV",
      "R": 217,
      "G": 182,
      "B": 151,
      "": ""
    },
    {
      "ImageCode": "L235C",
      "Color1": "L13",
      "Color2": "L25",
      "Color3": "L11",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LABW",
      "R": 216,
      "G": 180,
      "B": 146,
      "": ""
    },
    {
      "ImageCode": "L315B",
      "Color1": "L21",
      "Color2": "L23",
      "Color3": "L35",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LABX",
      "R": 214,
      "G": 174,
      "B": 138,
      "": ""
    },
    {
      "ImageCode": "L315C",
      "Color1": "L22",
      "Color2": "L31",
      "Color3": "L35",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LABY",
      "R": 210,
      "G": 170,
      "B": 135,
      "": ""
    },
    {
      "ImageCode": "L315D",
      "Color1": "M12",
      "Color2": "L35",
      "Color3": "L31",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LABY",
      "R": 210,
      "G": 170,
      "B": 135,
      "": ""
    },
    {
      "ImageCode": "L315E",
      "Color1": "M13",
      "Color2": "L35",
      "Color3": "L31",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LABY",
      "R": 210,
      "G": 170,
      "B": 135,
      "": ""
    },
    {
      "ImageCode": "L315F",
      "Color1": "L13",
      "Color2": "M15",
      "Color3": "L31",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "LABZ",
      "R": 206,
      "G": 166,
      "B": 131,
      "": ""
    },
    {
      "ImageCode": "L31C",
      "Color1": "L25",
      "Color2": "L31",
      "Color3": "L13",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LACA",
      "R": 214,
      "G": 173,
      "B": 138,
      "": ""
    },
    {
      "ImageCode": "L321D",
      "Color1": "L31",
      "Color2": "L32",
      "Color3": "M13",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LACB",
      "R": 209,
      "G": 165,
      "B": 134,
      "": ""
    },
    {
      "ImageCode": "L331A",
      "Color1": "L33",
      "Color2": "F21",
      "Color3": "F22",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LACC",
      "R": 213,
      "G": 175,
      "B": 145,
      "": ""
    },
    {
      "ImageCode": "L331B",
      "Color1": "L33",
      "Color2": "L35",
      "Color3": "L21",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LACD",
      "R": 210,
      "G": 170,
      "B": 138,
      "": ""
    },
    {
      "ImageCode": "L331E",
      "Color1": "L33",
      "Color2": "L21",
      "Color3": "M15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LACD",
      "R": 210,
      "G": 170,
      "B": 138,
      "": ""
    },
    {
      "ImageCode": "L331C",
      "Color1": "L31",
      "Color2": "L13",
      "Color3": "M25",
      "Part1": 0.5,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LACE",
      "R": 212,
      "G": 176,
      "B": 143,
      "": ""
    },
    {
      "ImageCode": "L331D",
      "Color1": "L31",
      "Color2": "M15",
      "Color3": "L33",
      "Part1": 0.5,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "LACF",
      "R": 206,
      "G": 166,
      "B": 135,
      "": ""
    },
    {
      "ImageCode": "L331F",
      "Color1": "L23",
      "Color2": "L31",
      "Color3": "L35",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "LACG",
      "R": 208,
      "G": 169,
      "B": 138,
      "": ""
    },
    {
      "ImageCode": "L331G",
      "Color1": "L33",
      "Color2": "M11",
      "Color3": "M15",
      "Part1": 1,
      "Part2": 0.5,
      "Part3": 0,
      "ComplexionCode": "LACH",
      "R": 204,
      "G": 164,
      "B": 133,
      "": ""
    },
    {
      "ImageCode": "M35C",
      "Color1": "M35",
      "Color2": "M33",
      "Color3": "M21",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0,
      "ComplexionCode": "MAAO",
      "R": 185,
      "G": 143,
      "B": 105,
      "": ""
    },
    {
      "ImageCode": "M245A",
      "Color1": "M24",
      "Color2": "M35",
      "Color3": "M25",
      "Part1": 3,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MAAS",
      "R": 190,
      "G": 143,
      "B": 112,
      "": ""
    },
    {
      "ImageCode": "M113A",
      "Color1": "M11",
      "Color2": "L33",
      "Color3": "L25",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MAAV",
      "R": 203,
      "G": 163,
      "B": 131,
      "": ""
    },
    {
      "ImageCode": "M113B",
      "Color1": "M13",
      "Color2": "M35",
      "Color3": "M11",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MAAW",
      "R": 197,
      "G": 158,
      "B": 127,
      "": ""
    },
    {
      "ImageCode": "M115B",
      "Color1": "M11",
      "Color2": "L35",
      "Color3": "L33",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MAAX",
      "R": 207,
      "G": 167,
      "B": 131,
      "": ""
    },
    {
      "ImageCode": "M115C",
      "Color1": "L21",
      "Color2": "L13",
      "Color3": "M15",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0.5,
      "ComplexionCode": "MAAY",
      "R": 212,
      "G": 171,
      "B": 136,
      "": ""
    },
    {
      "ImageCode": "M115D",
      "Color1": "L31",
      "Color2": "M15",
      "Color3": "L23",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MAAZ",
      "R": 206,
      "G": 166,
      "B": 131,
      "": ""
    },
    {
      "ImageCode": "M115G",
      "Color1": "L13",
      "Color2": "M15",
      "Color3": "L31",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "MAAZ",
      "R": 206,
      "G": 166,
      "B": 131,
      "": ""
    },
    {
      "ImageCode": "M115K",
      "Color1": "M15",
      "Color2": "L31",
      "Color3": "M13",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MAAZ",
      "R": 206,
      "G": 166,
      "B": 131,
      "": ""
    },
    {
      "ImageCode": "M151D",
      "Color1": "L31",
      "Color2": "M15",
      "Color3": "L23",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MAAZ",
      "R": 206,
      "G": 166,
      "B": 131,
      "": ""
    },
    {
      "ImageCode": "M115E",
      "Color1": "M15",
      "Color2": "L23",
      "Color3": "L11",
      "Part1": 1,
      "Part2": 0,
      "Part3": 2,
      "ComplexionCode": "MABA",
      "R": 212,
      "G": 173,
      "B": 140,
      "": ""
    },
    {
      "ImageCode": "M115F",
      "Color1": "L33",
      "Color2": "M15",
      "Color3": "L21",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "MABB",
      "R": 210,
      "G": 169,
      "B": 134,
      "": ""
    },
    {
      "ImageCode": "M115H",
      "Color1": "L33",
      "Color2": "M11",
      "Color3": "M25",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "MABC",
      "R": 201,
      "G": 159,
      "B": 122,
      "": ""
    },
    {
      "ImageCode": "M115I",
      "Color1": "L31",
      "Color2": "M23",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABD",
      "R": 205,
      "G": 163,
      "B": 126,
      "": ""
    },
    {
      "ImageCode": "M215E",
      "Color1": "L33",
      "Color2": "M25",
      "Color3": "L31",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "MABD",
      "R": 205,
      "G": 163,
      "B": 126,
      "": ""
    },
    {
      "ImageCode": "M115J",
      "Color1": "L31",
      "Color2": "M25",
      "Color3": "M13",
      "Part1": 2,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MABE",
      "R": 206,
      "G": 164,
      "B": 129,
      "": ""
    },
    {
      "ImageCode": "M215B",
      "Color1": "L31",
      "Color2": "L13",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0.5,
      "ComplexionCode": "MABE",
      "R": 206,
      "G": 164,
      "B": 129,
      "": ""
    },
    {
      "ImageCode": "M131A",
      "Color1": "M11",
      "Color2": "M25",
      "Color3": "L33",
      "Part1": 1,
      "Part2": 0,
      "Part3": 2,
      "ComplexionCode": "MABF",
      "R": 204,
      "G": 164,
      "B": 133,
      "": ""
    },
    {
      "ImageCode": "M131B",
      "Color1": "M11",
      "Color2": "M13",
      "Color3": "M35",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MABG",
      "R": 197,
      "G": 158,
      "B": 127,
      "": ""
    },
    {
      "ImageCode": "M135A",
      "Color1": "M15",
      "Color2": "L31",
      "Color3": "L33",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABH",
      "R": 204,
      "G": 166,
      "B": 132,
      "": ""
    },
    {
      "ImageCode": "M135B",
      "Color1": "M13",
      "Color2": "L35",
      "Color3": "L31",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MABI",
      "R": 202,
      "G": 165,
      "B": 132,
      "": ""
    },
    {
      "ImageCode": "M135C",
      "Color1": "L31",
      "Color2": "M25",
      "Color3": "M13",
      "Part1": 0,
      "Part2": 0.5,
      "Part3": 1,
      "ComplexionCode": "MABJ",
      "R": 195,
      "G": 157,
      "B": 125,
      "": ""
    },
    {
      "ImageCode": "M151C",
      "Color1": "M15",
      "Color2": "L11",
      "Color3": "L33",
      "Part1": 2,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MABK",
      "R": 208,
      "G": 169,
      "B": 134,
      "": ""
    },
    {
      "ImageCode": "M212C",
      "Color1": "M22",
      "Color2": "M21",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MABL",
      "R": 197,
      "G": 153,
      "B": 117,
      "": ""
    },
    {
      "ImageCode": "M213A",
      "Color1": "M21",
      "Color2": "M15",
      "Color3": "M13",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABM",
      "R": 194,
      "G": 155,
      "B": 123,
      "": ""
    },
    {
      "ImageCode": "M213D",
      "Color1": "M23",
      "Color2": "M35",
      "Color3": "M31",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABN",
      "R": 188,
      "G": 145,
      "B": 110,
      "": ""
    },
    {
      "ImageCode": "M215C",
      "Color1": "M25",
      "Color2": "M11",
      "Color3": "L23",
      "Part1": 1,
      "Part2": 2,
      "Part3": 0,
      "ComplexionCode": "MABO",
      "R": 202,
      "G": 159,
      "B": 123,
      "": ""
    },
    {
      "ImageCode": "M215G",
      "Color1": "M11",
      "Color2": "M23",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0.5,
      "ComplexionCode": "MABO",
      "R": 202,
      "G": 159,
      "B": 123,
      "": ""
    },
    {
      "ImageCode": "M215D",
      "Color1": "M25",
      "Color2": "M21",
      "Color3": "L33",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MABP",
      "R": 198,
      "G": 157,
      "B": 118,
      "": ""
    },
    {
      "ImageCode": "M215H",
      "Color1": "M21",
      "Color2": "M13",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABP",
      "R": 198,
      "G": 157,
      "B": 118,
      "": ""
    },
    {
      "ImageCode": "M215I",
      "Color1": "M25",
      "Color2": "M21",
      "Color3": "M13",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MABP",
      "R": 198,
      "G": 157,
      "B": 118,
      "": ""
    },
    {
      "ImageCode": "M251B",
      "Color1": "M21",
      "Color2": "M23",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABP",
      "R": 198,
      "G": 157,
      "B": 118,
      "": ""
    },
    {
      "ImageCode": "M215F",
      "Color1": "M21",
      "Color2": "M23",
      "Color3": "M15",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABQ",
      "R": 200,
      "G": 160,
      "B": 123,
      "": ""
    },
    {
      "ImageCode": "M215J",
      "Color1": "M21",
      "Color2": "M35",
      "Color3": "M33",
      "Part1": 1,
      "Part2": 0.5,
      "Part3": 0,
      "ComplexionCode": "MABR",
      "R": 193,
      "G": 151,
      "B": 113,
      "": ""
    },
    {
      "ImageCode": "M235B",
      "Color1": "L33",
      "Color2": "L31",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABS",
      "R": 202,
      "G": 163,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M235C",
      "Color1": "L31",
      "Color2": "L33",
      "Color3": "M25",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "MABS",
      "R": 202,
      "G": 163,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M235D",
      "Color1": "M11",
      "Color2": "M25",
      "Color3": "L33",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "MABS",
      "R": 202,
      "G": 163,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M235E",
      "Color1": "M11",
      "Color2": "L33",
      "Color3": "M25",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "MABS",
      "R": 202,
      "G": 163,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M235F",
      "Color1": "M13",
      "Color2": "M35",
      "Color3": "T11",
      "Part1": 2,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MABT",
      "R": 190,
      "G": 152,
      "B": 121,
      "": ""
    },
    {
      "ImageCode": "M253A",
      "Color1": "M13",
      "Color2": "M11",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABU",
      "R": 196,
      "G": 158,
      "B": 124,
      "": ""
    },
    {
      "ImageCode": "M253B",
      "Color1": "M25",
      "Color2": "M23",
      "Color3": "M11",
      "Part1": 1,
      "Part2": 0.5,
      "Part3": 0,
      "ComplexionCode": "MABV",
      "R": 197,
      "G": 156,
      "B": 119,
      "": ""
    },
    {
      "ImageCode": "M313A",
      "Color1": "M25",
      "Color2": "M33",
      "Color3": "M31",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "MABW",
      "R": 178,
      "G": 136,
      "B": 102,
      "": ""
    },
    {
      "ImageCode": "M315C",
      "Color1": "M35",
      "Color2": "M21",
      "Color3": "M33",
      "Part1": 1,
      "Part2": 2,
      "Part3": 0,
      "ComplexionCode": "MABX",
      "R": 193,
      "G": 151,
      "B": 113,
      "": ""
    },
    {
      "ImageCode": "M315D",
      "Color1": "M15",
      "Color2": "L22",
      "Color3": "M31",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MABY",
      "R": 194,
      "G": 153,
      "B": 115,
      "": ""
    },
    {
      "ImageCode": "M315E",
      "Color1": "M33",
      "Color2": "M21",
      "Color3": "T15",
      "Part1": 0,
      "Part2": 2,
      "Part3": 1,
      "ComplexionCode": "MABZ",
      "R": 190,
      "G": 148,
      "B": 109,
      "": ""
    },
    {
      "ImageCode": "M31D",
      "Color1": "M31",
      "Color2": "T11",
      "Color3": "M35",
      "Part1": 2,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MACA",
      "R": 182,
      "G": 138,
      "B": 99,
      "": ""
    },
    {
      "ImageCode": "M325A",
      "Color1": "M32",
      "Color2": "M35",
      "Color3": "M21",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MACB",
      "R": 187,
      "G": 140,
      "B": 103,
      "": ""
    },
    {
      "ImageCode": "M331A",
      "Color1": "M31",
      "Color2": "M33",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MACC",
      "R": 178,
      "G": 136,
      "B": 102,
      "": ""
    },
    {
      "ImageCode": "M331B",
      "Color1": "M35",
      "Color2": "M21",
      "Color3": "M33",
      "Part1": 0,
      "Part2": 1,
      "Part3": 2,
      "ComplexionCode": "MACD",
      "R": 179,
      "G": 139,
      "B": 107,
      "": ""
    },
    {
      "ImageCode": "M351C",
      "Color1": "M31",
      "Color2": "M33",
      "Color3": "M25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MACE",
      "R": 193,
      "G": 150,
      "B": 111,
      "": ""
    },
    {
      "ImageCode": "M351D",
      "Color1": "M31",
      "Color2": "M25",
      "Color3": "M33",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "MACE",
      "R": 193,
      "G": 150,
      "B": 111,
      "": ""
    },
    {
      "ImageCode": "M351E",
      "Color1": "M31",
      "Color2": "M23",
      "Color3": "M35",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "MACF",
      "R": 185,
      "G": 142,
      "B": 104,
      "": ""
    },
    {
      "ImageCode": "P11B",
      "Color1": "D23",
      "Color2": "P12",
      "Color3": "P11",
      "Part1": 2,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "PAAK",
      "R": 97,
      "G": 67,
      "B": 53,
      "": ""
    },
    {
      "ImageCode": "P125A",
      "Color1": "P11",
      "Color2": "P15",
      "Color3": "P12",
      "Part1": 0,
      "Part2": 1,
      "Part3": 2,
      "ComplexionCode": "PAAL",
      "R": 99,
      "G": 66,
      "B": 47,
      "": ""
    },
    {
      "ImageCode": "P21A",
      "Color1": "P21",
      "Color2": "P14",
      "Color3": "P22",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0,
      "ComplexionCode": "PAAM",
      "R": 84,
      "G": 56,
      "B": 42,
      "": ""
    },
    {
      "ImageCode": "P22A",
      "Color1": "D23",
      "Color2": "P11",
      "Color3": "P22",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "PAAN",
      "R": 91,
      "G": 63,
      "B": 49,
      "": ""
    },
    {
      "ImageCode": "P232A",
      "Color1": "P13",
      "Color2": "P22",
      "Color3": "P24",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "PAAO",
      "R": 81,
      "G": 56,
      "B": 44,
      "": ""
    },
    {
      "ImageCode": "T13A",
      "Color1": "T13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAC",
      "R": 165,
      "G": 123,
      "B": 91,
      "": ""
    },
    {
      "ImageCode": "T113A",
      "Color1": "T11",
      "Color2": "T15",
      "Color3": "T13",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TAAU",
      "R": 170,
      "G": 127,
      "B": 91,
      "": ""
    },
    {
      "ImageCode": "T113B",
      "Color1": "M33",
      "Color2": "T15",
      "Color3": "T11",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TAAV",
      "R": 173,
      "G": 131,
      "B": 96,
      "": ""
    },
    {
      "ImageCode": "T131A",
      "Color1": "T15",
      "Color2": "M33",
      "Color3": "T11",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "TAAV",
      "R": 173,
      "G": 131,
      "B": 96,
      "": ""
    },
    {
      "ImageCode": "T115A",
      "Color1": "T11",
      "Color2": "M35",
      "Color3": "T13",
      "Part1": 1,
      "Part2": 2,
      "Part3": 0,
      "ComplexionCode": "TAAW",
      "R": 182,
      "G": 139,
      "B": 101,
      "": ""
    },
    {
      "ImageCode": "T115C",
      "Color1": "T11",
      "Color2": "T15",
      "Color3": "M31",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TAAX",
      "R": 177,
      "G": 133,
      "B": 92,
      "": ""
    },
    {
      "ImageCode": "T115F",
      "Color1": "T23",
      "Color2": "T15",
      "Color3": "T11",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "TAAX",
      "R": 177,
      "G": 133,
      "B": 92,
      "": ""
    },
    {
      "ImageCode": "T151E",
      "Color1": "T15",
      "Color2": "T11",
      "Color3": "M33",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TAAX",
      "R": 177,
      "G": 133,
      "B": 92,
      "": ""
    },
    {
      "ImageCode": "T115D",
      "Color1": "T11",
      "Color2": "M33",
      "Color3": "M35",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TAAY",
      "R": 180,
      "G": 137,
      "B": 98,
      "": ""
    },
    {
      "ImageCode": "T115E",
      "Color1": "T15",
      "Color2": "M33",
      "Color3": "M31",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TAAZ",
      "R": 182,
      "G": 138,
      "B": 97,
      "": ""
    },
    {
      "ImageCode": "T115G",
      "Color1": "T15",
      "Color2": "M33",
      "Color3": "M31",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TAAZ",
      "R": 182,
      "G": 138,
      "B": 97,
      "": ""
    },
    {
      "ImageCode": "T115H",
      "Color1": "T11",
      "Color2": "T13",
      "Color3": "T35",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0.5,
      "ComplexionCode": "TABA",
      "R": 172,
      "G": 127,
      "B": 87,
      "": ""
    },
    {
      "ImageCode": "T11D",
      "Color1": "T11",
      "Color2": "T23",
      "Color3": "T25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0,
      "ComplexionCode": "TABB",
      "R": 175,
      "G": 131,
      "B": 91,
      "": ""
    },
    {
      "ImageCode": "T125C",
      "Color1": "T12",
      "Color2": "M35",
      "Color3": "T11",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABC",
      "R": 182,
      "G": 136,
      "B": 98,
      "": ""
    },
    {
      "ImageCode": "T131B",
      "Color1": "T25",
      "Color2": "T11",
      "Color3": "T13",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "TABD",
      "R": 170,
      "G": 127,
      "B": 91,
      "": ""
    },
    {
      "ImageCode": "T135C",
      "Color1": "T23",
      "Color2": "T15",
      "Color3": "T11",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABE",
      "R": 168,
      "G": 125,
      "B": 87,
      "": ""
    },
    {
      "ImageCode": "T151C",
      "Color1": "M31",
      "Color2": "T15",
      "Color3": "M33",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABF",
      "R": 182,
      "G": 138,
      "B": 97,
      "": ""
    },
    {
      "ImageCode": "T151D",
      "Color1": "T11",
      "Color2": "M25",
      "Color3": "T13",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABG",
      "R": 188,
      "G": 145,
      "B": 105,
      "": ""
    },
    {
      "ImageCode": "T212A",
      "Color1": "T11",
      "Color2": "T22",
      "Color3": "D15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABH",
      "R": 168,
      "G": 123,
      "B": 87,
      "": ""
    },
    {
      "ImageCode": "T212E",
      "Color1": "T11",
      "Color2": "T22",
      "Color3": "T15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABH",
      "R": 168,
      "G": 123,
      "B": 87,
      "": ""
    },
    {
      "ImageCode": "T212C",
      "Color1": "T31",
      "Color2": "T22",
      "Color3": "D15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABI",
      "R": 160,
      "G": 113,
      "B": 79,
      "": ""
    },
    {
      "ImageCode": "T213B",
      "Color1": "T21",
      "Color2": "T15",
      "Color3": "T23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TABJ",
      "R": 166,
      "G": 118,
      "B": 82,
      "": ""
    },
    {
      "ImageCode": "T213C",
      "Color1": "T11",
      "Color2": "T35",
      "Color3": "T23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TABK",
      "R": 166,
      "G": 123,
      "B": 87,
      "": ""
    },
    {
      "ImageCode": "T215B",
      "Color1": "T23",
      "Color2": "T25",
      "Color3": "M31",
      "Part1": 0,
      "Part2": 1,
      "Part3": 2,
      "ComplexionCode": "TABL",
      "R": 182,
      "G": 137,
      "B": 96,
      "": ""
    },
    {
      "ImageCode": "T215C",
      "Color1": "T35",
      "Color2": "M31",
      "Color3": "T23",
      "Part1": 1,
      "Part2": 2,
      "Part3": 0,
      "ComplexionCode": "TABM",
      "R": 179,
      "G": 134,
      "B": 94,
      "": ""
    },
    {
      "ImageCode": "T215D",
      "Color1": "T22",
      "Color2": "T11",
      "Color3": "T35",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "TABN",
      "R": 171,
      "G": 125,
      "B": 84,
      "": ""
    },
    {
      "ImageCode": "T215E",
      "Color1": "T25",
      "Color2": "M31",
      "Color3": "M33",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABO",
      "R": 180,
      "G": 134,
      "B": 93,
      "": ""
    },
    {
      "ImageCode": "T223C",
      "Color1": "T22",
      "Color2": "T35",
      "Color3": "T23",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TABP",
      "R": 159,
      "G": 115,
      "B": 83,
      "": ""
    },
    {
      "ImageCode": "T235B",
      "Color1": "T35",
      "Color2": "T13",
      "Color3": "T11",
      "Part1": 0.5,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABQ",
      "R": 166,
      "G": 122,
      "B": 87,
      "": ""
    },
    {
      "ImageCode": "T235C",
      "Color1": "T15",
      "Color2": "T23",
      "Color3": "T11",
      "Part1": 1,
      "Part2": 2,
      "Part3": 0,
      "ComplexionCode": "TABR",
      "R": 164,
      "G": 121,
      "B": 86,
      "": ""
    },
    {
      "ImageCode": "T235D",
      "Color1": "M33",
      "Color2": "D15",
      "Color3": "T11",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABS",
      "R": 164,
      "G": 122,
      "B": 85,
      "": ""
    },
    {
      "ImageCode": "T251C",
      "Color1": "M33",
      "Color2": "M31",
      "Color3": "T25",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "TABT",
      "R": 180,
      "G": 134,
      "B": 93,
      "": ""
    },
    {
      "ImageCode": "T312B",
      "Color1": "D15",
      "Color2": "T32",
      "Color3": "T31",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "TABU",
      "R": 157,
      "G": 109,
      "B": 75,
      "": ""
    },
    {
      "ImageCode": "T313B",
      "Color1": "T23",
      "Color2": "D15",
      "Color3": "T31",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TABV",
      "R": 159,
      "G": 113,
      "B": 78,
      "": ""
    },
    {
      "ImageCode": "T315C",
      "Color1": "D15",
      "Color2": "T23",
      "Color3": "T31",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TABW",
      "R": 159,
      "G": 112,
      "B": 72,
      "": ""
    },
    {
      "ImageCode": "T323B",
      "Color1": "T32",
      "Color2": "T23",
      "Color3": "D15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABX",
      "R": 156,
      "G": 112,
      "B": 79,
      "": ""
    },
    {
      "ImageCode": "T332A",
      "Color1": "T32",
      "Color2": "T23",
      "Color3": "D25",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABX",
      "R": 156,
      "G": 112,
      "B": 79,
      "": ""
    },
    {
      "ImageCode": "T332B",
      "Color1": "T32",
      "Color2": "T23",
      "Color3": "D15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABX",
      "R": 156,
      "G": 112,
      "B": 79,
      "": ""
    },
    {
      "ImageCode": "T324B",
      "Color1": "T24",
      "Color2": "T32",
      "Color3": "M12",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TABY",
      "R": 161,
      "G": 110,
      "B": 77,
      "": ""
    },
    {
      "ImageCode": "T325C",
      "Color1": "T22",
      "Color2": "T33",
      "Color3": "D25",
      "Part1": 1,
      "Part2": 0,
      "Part3": 1,
      "ComplexionCode": "TABZ",
      "R": 147,
      "G": 106,
      "B": 73,
      "": ""
    },
    {
      "ImageCode": "T331C",
      "Color1": "T11",
      "Color2": "T23",
      "Color3": "D15",
      "Part1": 0.5,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TACA",
      "R": 163,
      "G": 121,
      "B": 85,
      "": ""
    },
    {
      "ImageCode": "T331D",
      "Color1": "D15",
      "Color2": "T23",
      "Color3": "T31",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "TACB",
      "R": 159,
      "G": 113,
      "B": 78,
      "": ""
    },
    {
      "ImageCode": "T332C",
      "Color1": "T33",
      "Color2": "D22",
      "Color3": "P15",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TACC",
      "R": 125,
      "G": 83,
      "B": 51,
      "": ""
    },
    {
      "ImageCode": "T335A",
      "Color1": "T22",
      "Color2": "T23",
      "Color3": "D25",
      "Part1": 0,
      "Part2": 1,
      "Part3": 1,
      "ComplexionCode": "TACD",
      "R": 146,
      "G": 106,
      "B": 73,
      "": ""
    },
    {
      "ImageCode": "T33B",
      "Color1": "D15",
      "Color2": "T33",
      "Color3": "D11",
      "Part1": 1,
      "Part2": 1,
      "Part3": 0,
      "ComplexionCode": "TACE",
      "R": 143,
      "G": 100,
      "B": 62,
      "": ""
    },
    {
      "ImageCode": "D11A",
      "Color1": "D11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0,
      "ComplexionCode": "DAAA",
      "R": 135,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D11B",
      "Color1": "D11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAA",
      "R": 135,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D11C",
      "Color1": "D11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAA",
      "R": 135,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D11D",
      "Color1": "D11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAA",
      "R": 135,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D11E",
      "Color1": "D11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAA",
      "R": 135,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D11F",
      "Color1": "D11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAA",
      "R": 135,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D11G",
      "Color1": "D11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAA",
      "R": 135,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D11H",
      "Color1": "D11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAA",
      "R": 135,
      "G": 89,
      "B": 52,
      "": ""
    },
    {
      "ImageCode": "D12A",
      "Color1": "D12",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0,
      "ComplexionCode": "DAAB",
      "R": 136,
      "G": 88,
      "B": 51,
      "": ""
    },
    {
      "ImageCode": "D112A",
      "Color1": "D12",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAB",
      "R": 136,
      "G": 88,
      "B": 51,
      "": ""
    },
    {
      "ImageCode": "D13D",
      "Color1": "D13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0,
      "ComplexionCode": "DAAC",
      "R": 106,
      "G": 77,
      "B": 62,
      "": ""
    },
    {
      "ImageCode": "D131A",
      "Color1": "D13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAC",
      "R": 106,
      "G": 77,
      "B": 62,
      "": ""
    },
    {
      "ImageCode": "D13B",
      "Color1": "D13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAC",
      "R": 106,
      "G": 77,
      "B": 62,
      "": ""
    },
    {
      "ImageCode": "D13C",
      "Color1": "D13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAC",
      "R": 106,
      "G": 77,
      "B": 62,
      "": ""
    },
    {
      "ImageCode": "D21F",
      "Color1": "D21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0,
      "ComplexionCode": "DAAF",
      "R": 122,
      "G": 80,
      "B": 50,
      "": ""
    },
    {
      "ImageCode": "D241C",
      "Color1": "D21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAF",
      "R": 122,
      "G": 80,
      "B": 50,
      "": ""
    },
    {
      "ImageCode": "D21H",
      "Color1": "D21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAF",
      "R": 122,
      "G": 80,
      "B": 50,
      "": ""
    },
    {
      "ImageCode": "D22B",
      "Color1": "D22",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAG",
      "R": 122,
      "G": 79,
      "B": 49,
      "": ""
    },
    {
      "ImageCode": "D22C",
      "Color1": "D22",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAG",
      "R": 122,
      "G": 79,
      "B": 49,
      "": ""
    },
    {
      "ImageCode": "D22D",
      "Color1": "D22",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAG",
      "R": 122,
      "G": 79,
      "B": 49,
      "": ""
    },
    {
      "ImageCode": "D22E",
      "Color1": "D22",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAG",
      "R": 122,
      "G": 79,
      "B": 49,
      "": ""
    },
    {
      "ImageCode": "D23B",
      "Color1": "D23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAH",
      "R": 98,
      "G": 70,
      "B": 57,
      "": ""
    },
    {
      "ImageCode": "D24A",
      "Color1": "D24",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": 0,
      "Part3": 0,
      "ComplexionCode": "DAAI",
      "R": 104,
      "G": 72,
      "B": 55,
      "": ""
    },
    {
      "ImageCode": "D24A",
      "Color1": "D24",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAI",
      "R": 104,
      "G": 72,
      "B": 55,
      "": ""
    },
    {
      "ImageCode": "D25A",
      "Color1": "D25",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAJ",
      "R": 134,
      "G": 96,
      "B": 63,
      "": ""
    },
    {
      "ImageCode": "D25B",
      "Color1": "D25",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "DAAJ",
      "R": 134,
      "G": 96,
      "B": 63,
      "": ""
    },
    {
      "ImageCode": "F12A",
      "Color1": "F12",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAB",
      "R": 233,
      "G": 195,
      "B": 169,
      "": ""
    },
    {
      "ImageCode": "F13C",
      "Color1": "F13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAC",
      "R": 215,
      "G": 189,
      "B": 166,
      "": ""
    },
    {
      "ImageCode": "F13E",
      "Color1": "F13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAC",
      "R": 215,
      "G": 189,
      "B": 166,
      "": ""
    },
    {
      "ImageCode": "F21C",
      "Color1": "F21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAF",
      "R": 221,
      "G": 184,
      "B": 154,
      "": ""
    },
    {
      "ImageCode": "F23C",
      "Color1": "F23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAH",
      "R": 214,
      "G": 186,
      "B": 157,
      "": ""
    },
    {
      "ImageCode": "F234B",
      "Color1": "F23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAH",
      "R": 214,
      "G": 186,
      "B": 157,
      "": ""
    },
    {
      "ImageCode": "F235A",
      "Color1": "F23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAH",
      "R": 214,
      "G": 186,
      "B": 157,
      "": ""
    },
    {
      "ImageCode": "F13G",
      "Color1": "F13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAH",
      "R": 214,
      "G": 186,
      "B": 157,
      "": ""
    },
    {
      "ImageCode": "F23E",
      "Color1": "F23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAH",
      "R": 214,
      "G": 186,
      "B": 157,
      "": ""
    },
    {
      "ImageCode": "F23G",
      "Color1": "F23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAH",
      "R": 214,
      "G": 186,
      "B": 157,
      "": ""
    },
    {
      "ImageCode": "F23H",
      "Color1": "F23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "FAAH",
      "R": 214,
      "G": 186,
      "B": 157,
      "": ""
    },
    {
      "ImageCode": "L11B",
      "Color1": "L11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAA",
      "R": 216,
      "G": 177,
      "B": 145,
      "": ""
    },
    {
      "ImageCode": "L11M",
      "Color1": "L11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAA",
      "R": 216,
      "G": 177,
      "B": 145,
      "": ""
    },
    {
      "ImageCode": "L11O",
      "Color1": "L11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAA",
      "R": 216,
      "G": 177,
      "B": 145,
      "": ""
    },
    {
      "ImageCode": "L11R",
      "Color1": "L11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAA",
      "R": 216,
      "G": 177,
      "B": 145,
      "": ""
    },
    {
      "ImageCode": "L11U",
      "Color1": "L11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAA",
      "R": 216,
      "G": 177,
      "B": 145,
      "": ""
    },
    {
      "ImageCode": "L11V",
      "Color1": "L11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAA",
      "R": 216,
      "G": 177,
      "B": 145,
      "": ""
    },
    {
      "ImageCode": "L11W",
      "Color1": "L11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAA",
      "R": 216,
      "G": 177,
      "B": 145,
      "": ""
    },
    {
      "ImageCode": "L13B",
      "Color1": "L13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAC",
      "R": 213,
      "G": 180,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L13G",
      "Color1": "L13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAC",
      "R": 213,
      "G": 180,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L13I",
      "Color1": "L13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAC",
      "R": 213,
      "G": 180,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L13J",
      "Color1": "L13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAC",
      "R": 213,
      "G": 180,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L13K",
      "Color1": "L13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAC",
      "R": 213,
      "G": 180,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L13L",
      "Color1": "L13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAC",
      "R": 213,
      "G": 180,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L13M",
      "Color1": "L13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAC",
      "R": 213,
      "G": 180,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L13N",
      "Color1": "L13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAC",
      "R": 213,
      "G": 180,
      "B": 148,
      "": ""
    },
    {
      "ImageCode": "L21I",
      "Color1": "L21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAF",
      "R": 216,
      "G": 173,
      "B": 139,
      "": ""
    },
    {
      "ImageCode": "L21J",
      "Color1": "L21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAF",
      "R": 216,
      "G": 173,
      "B": 139,
      "": ""
    },
    {
      "ImageCode": "L21K",
      "Color1": "L21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAF",
      "R": 216,
      "G": 173,
      "B": 139,
      "": ""
    },
    {
      "ImageCode": "L23C",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23D",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23E",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23F",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23G",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23H",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23I",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23J",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23A",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23K",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L23L",
      "Color1": "L23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAH",
      "R": 207,
      "G": 171,
      "B": 142,
      "": ""
    },
    {
      "ImageCode": "L21F",
      "Color1": "L21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAJ",
      "R": 217,
      "G": 178,
      "B": 144,
      "": ""
    },
    {
      "ImageCode": "L31D",
      "Color1": "L31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAK",
      "R": 209,
      "G": 166,
      "B": 133,
      "": ""
    },
    {
      "ImageCode": "L31E",
      "Color1": "L31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAK",
      "R": 209,
      "G": 166,
      "B": 133,
      "": ""
    },
    {
      "ImageCode": "L31F",
      "Color1": "L31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAK",
      "R": 209,
      "G": 166,
      "B": 133,
      "": ""
    },
    {
      "ImageCode": "L31G",
      "Color1": "L31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAK",
      "R": 209,
      "G": 166,
      "B": 133,
      "": ""
    },
    {
      "ImageCode": "L31H",
      "Color1": "L31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAK",
      "R": 209,
      "G": 166,
      "B": 133,
      "": ""
    },
    {
      "ImageCode": "L31I",
      "Color1": "L31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAK",
      "R": 209,
      "G": 166,
      "B": 133,
      "": ""
    },
    {
      "ImageCode": "L32D",
      "Color1": "L32",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAL",
      "R": 208,
      "G": 163,
      "B": 134,
      "": ""
    },
    {
      "ImageCode": "L35B",
      "Color1": "L35",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "LAAO",
      "R": 211,
      "G": 174,
      "B": 136,
      "": ""
    },
    {
      "ImageCode": "M11B",
      "Color1": "M11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAA",
      "R": 202,
      "G": 159,
      "B": 125,
      "": ""
    },
    {
      "ImageCode": "M11C",
      "Color1": "M11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAA",
      "R": 202,
      "G": 159,
      "B": 125,
      "": ""
    },
    {
      "ImageCode": "M11D",
      "Color1": "M11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAA",
      "R": 202,
      "G": 159,
      "B": 125,
      "": ""
    },
    {
      "ImageCode": "M11E",
      "Color1": "M11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAA",
      "R": 202,
      "G": 159,
      "B": 125,
      "": ""
    },
    {
      "ImageCode": "M11F",
      "Color1": "M11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAA",
      "R": 202,
      "G": 159,
      "B": 125,
      "": ""
    },
    {
      "ImageCode": "M12C",
      "Color1": "M12",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAB",
      "R": 206,
      "G": 159,
      "B": 127,
      "": ""
    },
    {
      "ImageCode": "M13A",
      "Color1": "M13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAC",
      "R": 192,
      "G": 156,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M13B",
      "Color1": "M13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAC",
      "R": 192,
      "G": 156,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M13D",
      "Color1": "M13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAC",
      "R": 192,
      "G": 156,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M35C",
      "Color1": "M35",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAC",
      "R": 192,
      "G": 156,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M15C",
      "Color1": "M15",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAE",
      "R": 203,
      "G": 165,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M15D",
      "Color1": "M15",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAE",
      "R": 203,
      "G": 165,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M15E",
      "Color1": "M15",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAE",
      "R": 203,
      "G": 165,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M15F",
      "Color1": "M15",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAE",
      "R": 203,
      "G": 165,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M15G",
      "Color1": "M15",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAE",
      "R": 203,
      "G": 165,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M15G",
      "Color1": "M15",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAE",
      "R": 203,
      "G": 165,
      "B": 128,
      "": ""
    },
    {
      "ImageCode": "M21F",
      "Color1": "M21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAF",
      "R": 196,
      "G": 154,
      "B": 117,
      "": ""
    },
    {
      "ImageCode": "M21I",
      "Color1": "M21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAF",
      "R": 196,
      "G": 154,
      "B": 117,
      "": ""
    },
    {
      "ImageCode": "M21E",
      "Color1": "M21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAF",
      "R": 196,
      "G": 154,
      "B": 117,
      "": ""
    },
    {
      "ImageCode": "M21F",
      "Color1": "M21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAF",
      "R": 196,
      "G": 154,
      "B": 117,
      "": ""
    },
    {
      "ImageCode": "M21G",
      "Color1": "M21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAF",
      "R": 196,
      "G": 154,
      "B": 117,
      "": ""
    },
    {
      "ImageCode": "M21J",
      "Color1": "M21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAF",
      "R": 196,
      "G": 154,
      "B": 117,
      "": ""
    },
    {
      "ImageCode": "M21K",
      "Color1": "M21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAF",
      "R": 196,
      "G": 154,
      "B": 117,
      "": ""
    },
    {
      "ImageCode": "M21L",
      "Color1": "M21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAF",
      "R": 196,
      "G": 154,
      "B": 117,
      "": ""
    },
    {
      "ImageCode": "M22C",
      "Color1": "M22",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAG",
      "R": 197,
      "G": 151,
      "B": 116,
      "": ""
    },
    {
      "ImageCode": "M23A",
      "Color1": "M23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAH",
      "R": 190,
      "G": 148,
      "B": 118,
      "": ""
    },
    {
      "ImageCode": "M25B",
      "Color1": "M25",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAJ",
      "R": 200,
      "G": 159,
      "B": 119,
      "": ""
    },
    {
      "ImageCode": "M25C",
      "Color1": "M25",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAJ",
      "R": 200,
      "G": 159,
      "B": 119,
      "": ""
    },
    {
      "ImageCode": "M31B",
      "Color1": "M31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAK",
      "R": 185,
      "G": 141,
      "B": 102,
      "": ""
    },
    {
      "ImageCode": "M31E",
      "Color1": "M31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAK",
      "R": 185,
      "G": 141,
      "B": 102,
      "": ""
    },
    {
      "ImageCode": "M31F",
      "Color1": "M31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAK",
      "R": 185,
      "G": 141,
      "B": 102,
      "": ""
    },
    {
      "ImageCode": "M31G",
      "Color1": "M31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAK",
      "R": 185,
      "G": 141,
      "B": 102,
      "": ""
    },
    {
      "ImageCode": "M31I",
      "Color1": "M31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAK",
      "R": 185,
      "G": 141,
      "B": 102,
      "": ""
    },
    {
      "ImageCode": "M32C",
      "Color1": "M32",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAL",
      "R": 188,
      "G": 137,
      "B": 101,
      "": ""
    },
    {
      "ImageCode": "M32D",
      "Color1": "M32",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAL",
      "R": 188,
      "G": 137,
      "B": 101,
      "": ""
    },
    {
      "ImageCode": "M33B",
      "Color1": "M33",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAM",
      "R": 170,
      "G": 131,
      "B": 101,
      "": ""
    },
    {
      "ImageCode": "M31H",
      "Color1": "M31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "MAAM",
      "R": 170,
      "G": 131,
      "B": 101,
      "": ""
    },
    {
      "ImageCode": "P11C",
      "Color1": "P11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAA",
      "R": 94,
      "G": 60,
      "B": 43,
      "": ""
    },
    {
      "ImageCode": "P11D",
      "Color1": "P11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAA",
      "R": 94,
      "G": 60,
      "B": 43,
      "": ""
    },
    {
      "ImageCode": "P11E",
      "Color1": "P11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAA",
      "R": 94,
      "G": 60,
      "B": 43,
      "": ""
    },
    {
      "ImageCode": "P11F",
      "Color1": "P11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAA",
      "R": 94,
      "G": 60,
      "B": 43,
      "": ""
    },
    {
      "ImageCode": "P12A",
      "Color1": "P12",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAB",
      "R": 94,
      "G": 59,
      "B": 43,
      "": ""
    },
    {
      "ImageCode": "P13B",
      "Color1": "P13",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAC",
      "R": 77,
      "G": 55,
      "B": 47,
      "": ""
    },
    {
      "ImageCode": "P14B",
      "Color1": "P14",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAD",
      "R": 92,
      "G": 59,
      "B": 42,
      "": ""
    },
    {
      "ImageCode": "P14C",
      "Color1": "P14",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAD",
      "R": 92,
      "G": 59,
      "B": 42,
      "": ""
    },
    {
      "ImageCode": "P15A",
      "Color1": "P15",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAE",
      "R": 108,
      "G": 78,
      "B": 53,
      "": ""
    },
    {
      "ImageCode": "P22B",
      "Color1": "P22",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAG",
      "R": 84,
      "G": 56,
      "B": 41,
      "": ""
    },
    {
      "ImageCode": "P23B",
      "Color1": "P23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAH",
      "R": 63,
      "G": 43,
      "B": 38,
      "": ""
    },
    {
      "ImageCode": "P23C",
      "Color1": "P23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAH",
      "R": 63,
      "G": 43,
      "B": 38,
      "": ""
    },
    {
      "ImageCode": "P23D",
      "Color1": "P23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAH",
      "R": 63,
      "G": 43,
      "B": 38,
      "": ""
    },
    {
      "ImageCode": "P24B",
      "Color1": "P24",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "PAAI",
      "R": 56,
      "G": 38,
      "B": 33,
      "": ""
    },
    {
      "ImageCode": "T11C",
      "Color1": "T11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAA",
      "R": 175,
      "G": 131,
      "B": 91,
      "": ""
    },
    {
      "ImageCode": "T11D",
      "Color1": "T11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAA",
      "R": 175,
      "G": 131,
      "B": 91,
      "": ""
    },
    {
      "ImageCode": "T11E",
      "Color1": "T11",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAA",
      "R": 175,
      "G": 131,
      "B": 91,
      "": ""
    },
    {
      "ImageCode": "T15F",
      "Color1": "T15",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAE",
      "R": 178,
      "G": 134,
      "B": 92,
      "": ""
    },
    {
      "ImageCode": "T15G",
      "Color1": "T15",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAE",
      "R": 178,
      "G": 134,
      "B": 92,
      "": ""
    },
    {
      "ImageCode": "T21E",
      "Color1": "T21",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAF",
      "R": 174,
      "G": 120,
      "B": 82,
      "": ""
    },
    {
      "ImageCode": "T23B",
      "Color1": "T23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAH",
      "R": 157,
      "G": 115,
      "B": 82,
      "": ""
    },
    {
      "ImageCode": "T23C",
      "Color1": "T23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAH",
      "R": 157,
      "G": 115,
      "B": 82,
      "": ""
    },
    {
      "ImageCode": "T23D",
      "Color1": "T23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAH",
      "R": 157,
      "G": 115,
      "B": 82,
      "": ""
    },
    {
      "ImageCode": "T23E",
      "Color1": "T23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAH",
      "R": 157,
      "G": 115,
      "B": 82,
      "": ""
    },
    {
      "ImageCode": "T23A",
      "Color1": "T23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAH",
      "R": 157,
      "G": 115,
      "B": 82,
      "": ""
    },
    {
      "ImageCode": "T23F",
      "Color1": "T23",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAH",
      "R": 157,
      "G": 115,
      "B": 82,
      "": ""
    },
    {
      "ImageCode": "T31C",
      "Color1": "T31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAK",
      "R": 160,
      "G": 110,
      "B": 74,
      "": ""
    },
    {
      "ImageCode": "T31A",
      "Color1": "T31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAK",
      "R": 160,
      "G": 110,
      "B": 74,
      "": ""
    },
    {
      "ImageCode": "T31B",
      "Color1": "T31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAK",
      "R": 160,
      "G": 110,
      "B": 74,
      "": ""
    },
    {
      "ImageCode": "T31D",
      "Color1": "T31",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAK",
      "R": 160,
      "G": 110,
      "B": 74,
      "": ""
    },
    {
      "ImageCode": "T32C",
      "Color1": "T32",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAL",
      "R": 154,
      "G": 108,
      "B": 75,
      "": ""
    },
    {
      "ImageCode": "T32D",
      "Color1": "T32",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAL",
      "R": 154,
      "G": 108,
      "B": 75,
      "": ""
    },
    {
      "ImageCode": "T32E",
      "Color1": "T32",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAL",
      "R": 154,
      "G": 108,
      "B": 75,
      "": ""
    },
    {
      "ImageCode": "T33C",
      "Color1": "T33",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAM",
      "R": 128,
      "G": 86,
      "B": 53,
      "": ""
    },
    {
      "ImageCode": "T33A",
      "Color1": "T33",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAM",
      "R": 128,
      "G": 86,
      "B": 53,
      "": ""
    },
    {
      "ImageCode": "T35B",
      "Color1": "T35",
      "Color2": "",
      "Color3": "",
      "Part1": 1,
      "Part2": "",
      "Part3": "",
      "ComplexionCode": "TAAO",
      "R": 166,
      "G": 119,
      "B": 77,
      "": ""
    }
  ]

  const colors = getMappedData()
  const nearest = NearestColor.from(colors)
  const nearestRGBFormula = nearest('red')
})()